site_name: Project North Star

nav:
  - Getting Started:
      - Home: README.md
      - Community Links: community-links.md
  - Mechanical:
      - Getting Started: mechanical/README.md
      - Leap Motion Version 3:
          - Getting Started: mechanical/leap-motion-v3/README.md
          - Bill of Materials: mechanical/leap-motion-v3/headset-bom.md
          - Assembly Guide: mechanical/leap-motion-v3/headset-assembly.md
      - Leap Motion Version 1:
          - Assembly Guide: mechanical/leap-motion-v1/v1-assembly-guide.md
          - 3D Print Reference: mechanical/leap-motion-v1/v1-3d-print-reference.md
      - Smart Prototyping Kits: mechanical/smart-prototyping-kits.md
      - Exii Version 1: https://exiii.jp/2018/07/25/project_north_star_en/
      - Changelog: mechanical/changelog.md
  - Software:
      - Getting Started: software/getting-started.md
      - SteamVR: software/steamvr.md
      - FAQ: software/README.md
  - Calibration:
      - Getting Started: calibration/README.md
      - Version 1: calibration/calibration-v1.md
      - Version 2: calibration/calibration-v2.md
  - Electronics:
      - Electronics: electronics/electronics.md
      - Firmware: electronics/firmware.md
      - Schematics: electronics/schematics.md
  - Community Links:
      - Discord: https://discordapp.com/invite/NghjdX7
      - Twitter: https://twitter.com/search?q=%23ProjectNorthStar
      - Reddit: https://www.reddit.com/r/ProjectNorthStar/
      - Leap Motion Forums: https://forums.leapmotion.com/t/project-north-star/7071
  - Leap Motion Blogs:
      - Blog: http://blog.leapmotion.com/tag/north-star/
      - Bending Reality North Starâ€™s Calibration System: http://blog.leapmotion.com/bending-reality-north-stars-calibration-system/
      - Project North Star Mechanical Update 3: http://blog.leapmotion.com/project-north-star-mechanical-update-3/
      - Project North Star Mechanical and Calibration Update 3.1: http://blog.leapmotion.com/project-north-star-mechanical-and-calibration-update-3-1/
      - Project North Star Mechanical Update 1: http://blog.leapmotion.com/project-north-star-mechanical-update-1/
      - Project North Star is Now Open Source: http://blog.leapmotion.com/north-star-open-source/
      - Our Journey to the North Star: http://blog.leapmotion.com/our-journey-to-the-north-star/
      - Unveiling Project North Star: http://blog.leapmotion.com/northstar/



theme: flatly

markdown_extensions:
  - admonition